In [2]:
import pandas as pd
import numpy as np

In [14]:
nppes = pd.read_parquet('../data/processed/nppes_dental_providers.parquet')
cbp = pd.read_parquet('../data/processed/cbp_dental_2018_2023.parquet')
gcspi = pd.read_parquet('../data/processed/gscpi.parquet')
acs = pd.read_parquet('../data/processed/acs_demographics_2021.parquet')

In [37]:
cbp

,ESTAB,EMP,PAYANN,NAME,NAICS2017,state,county
0,5,27,1072,"Prince Edward County, Virginia",621210,51,147
1,19,201,10488,"Rockingham County, Virginia",621210,51,165
2,3,21,1257,"Scott County, Virginia",621210,51,169
3,40,324,17720,"Spotsylvania County, Virginia",621210,51,177
4,3,13,683,"Clarke County, Virginia",621210,51,043
...,...,...,...,...,...,...,...
13129,4,12,150,"Villalba Municipio, Puerto Rico",621210,72,149
13130,5,23,473,"Yabucoa Municipio, Puerto Rico",621210,72,151
13131,10,35,815,"Yauco Municipio, Puerto Rico",621210,72,153
13132,12,55,2862,"St. Croix Island, United States Virgin Islands",621210,78,010
13133,12,104,6127,"St. Thomas Island, United States Virgin Islands",621210,78,030

In [31]:
len(acs['county'].values.unique())

326

In [32]:
acs

,B19013_001E,B01002_001E,B27001_001E,B27001_004E,B27001_007E,B27001_010E,B27001_013E,B27001_016E,B27001_019E,B27001_022E,...,B27001_041E,B27001_044E,B27001_047E,B27001_050E,B27001_053E,B27001_056E,state,county,insured_total,pct_insured
0,62660.0,38.5,56955.0,2191.0,4853.0,2012.0,2372.0,2665.0,3665.0,3329.0,...,2962.0,3488.0,3819.0,3414.0,2782.0,1995.0,01,001,52459.0,92.106049
1,64346.0,43.4,224339.0,7057.0,17568.0,7060.0,7338.0,10647.0,12194.0,14169.0,...,9015.0,12480.0,13222.0,16093.0,14902.0,9647.0,01,003,202513.0,90.270974
2,36422.0,40.2,22295.0,749.0,1959.0,625.0,920.0,771.0,1153.0,1180.0,...,944.0,1078.0,1186.0,1422.0,1572.0,1075.0,01,005,19982.0,89.625477
3,54277.0,39.7,21000.0,726.0,1753.0,786.0,1223.0,1205.0,1167.0,1323.0,...,908.0,1083.0,1245.0,1242.0,1076.0,811.0,01,007,18905.0,90.023810
4,52830.0,41.1,58437.0,1956.0,5083.0,2187.0,2184.0,2817.0,3541.0,3684.0,...,2563.0,2946.0,3053.0,3672.0,3246.0,2429.0,01,009,52583.0,89.982374
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3216,21507.0,43.1,54340.0,1156.0,3946.0,1856.0,2511.0,2658.0,2937.0,3004.0,...,2812.0,3209.0,3357.0,3631.0,3274.0,2999.0,72,145,49128.0,90.408539
3217,14942.0,43.6,8317.0,333.0,502.0,302.0,163.0,362.0,321.0,573.0,...,40.0,457.0,463.0,549.0,521.0,470.0,72,147,7181.0,86.341229
3218,20722.0,42.0,22237.0,645.0,1795.0,984.0,1137.0,1059.0,1211.0,1456.0,...,1261.0,1257.0,1440.0,1720.0,1350.0,931.0,72,149,21530.0,96.820614
3219,17267.0,44.9,31042.0,634.0,2330.0,1322.0,1240.0,1458.0,1806.0,1989.0,...,1568.0,1785.0,2018.0,2187.0,2029.0,1614.0,72,151,29295.0,94.372141
3220,16444.0,45.5,34557.0,781.0,2605.0,1499.0,1490.0,1522.0,2041.0,1998.0,...,1697.0,2103.0,2215.0,2529.0,2376.0,1997.0,72,153,32521.0,94.108285

In [36]:
acs.groupby('state')['county'].nunique().sum()

np.int64(3221)

In [ ]:
nppes['county'] = nppes["practice_location_postal"].map(crosswalk['COUNTY'])

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [10]:
crosswalk = pd.read_excel('..\ZIP_COUNTY_122025.xlsx', sheet_name='Export Worksheet', dtype={'ZIP': str, 'COUNTY': str})

<>:1: SyntaxWarning: invalid escape sequence '\Z'
<>:1: SyntaxWarning: invalid escape sequence '\Z'
C:\Users\CMarco\AppData\Local\Temp\ipykernel_25256\392708273.py:1: SyntaxWarning: invalid escape sequence '\Z'
  crosswalk = pd.read_excel('..\ZIP_COUNTY_122025.xlsx', sheet_name='Export Worksheet', dtype={'ZIP': str, 'COUNTY': str})

In [12]:
crosswalk

,ZIP,COUNTY,USPS_ZIP_PREF_CITY,USPS_ZIP_PREF_STATE,RES_RATIO,BUS_RATIO,OTH_RATIO,TOT_RATIO
0,00501,36103,HOLTSVILLE,NY,0.000000,1.000000,0.000000,1.000000
1,00601,72081,ADJUNTAS,PR,0.002549,0.005051,0.012048,0.002947
2,00601,72001,ADJUNTAS,PR,0.997451,0.994949,0.987952,0.997053
3,00602,72117,AGUADA,PR,0.000584,0.000000,0.000000,0.000530
4,00602,72005,AGUADA,PR,0.000000,0.001016,0.000000,0.000076
...,...,...,...,...,...,...,...,...
54566,99926,02198,METLAKATLA,AK,1.000000,0.000000,1.000000,1.000000
54567,99927,02198,POINT BAKER,AK,0.000000,0.000000,1.000000,1.000000
54568,99928,02130,WARD COVE,AK,0.000000,0.000000,1.000000,1.000000
54569,99929,02275,WRANGELL,AK,1.000000,1.000000,1.000000,1.000000
54570,99950,02198,KETCHIKAN,AK,1.000000,0.000000,0.000000,1.000000