In [1]:
import pandas as pd

In [2]:
use_cols = ['NPI', 'Entity Type Code', 'Provider Organization Name (Legal Business Name)',
            'Provider First Name', 'Provider Last Name (Legal Name)', 'Provider First Line Business Mailing Address',
            'Provider First Line Business Practice Location Address',
            'Healthcare Provider Taxonomy Code_1',
            'Healthcare Provider Taxonomy Code_2',
            'Provider Business Practice Location Address Postal Code',
            'Provider Business Practice Location Address State Name']

codes = [
    '1223G0001X', '1223D0001X', '1223E0200X', '1223P0221X',
    '1223P0300X', '1223P0700X', '1223S0112X', '1223X0400X',
    '122300000X', '1223D0008X', '1223X0008X'
]

In [3]:
chunks = []

for chunk in pd.read_csv('../npidata_pfile_20050523-20260308.csv', low_memory=False, usecols=use_cols, chunksize=50000):
    mask = chunk[[c for c in chunk.columns if "taxonomy code_" in c.lower()]].isin(codes).any(axis=1)
    filtered_chunk = chunk[mask]
    if len(filtered_chunk) > 0:
        chunks.append(filtered_chunk)
    print(f"Processed chunk with {len(chunk)} rows, found {len(filtered_chunk)} matches.")

df = pd.concat(chunks, ignore_index=True)

Processed chunk with 50000 rows, found 2495 matches.
Processed chunk with 50000 rows, found 1679 matches.
Processed chunk with 50000 rows, found 1591 matches.
Processed chunk with 50000 rows, found 2638 matches.
Processed chunk with 50000 rows, found 1853 matches.
Processed chunk with 50000 rows, found 2251 matches.
Processed chunk with 50000 rows, found 1774 matches.
Processed chunk with 50000 rows, found 1329 matches.
Processed chunk with 50000 rows, found 1762 matches.
Processed chunk with 50000 rows, found 1469 matches.
Processed chunk with 50000 rows, found 1248 matches.
Processed chunk with 50000 rows, found 991 matches.
Processed chunk with 50000 rows, found 1312 matches.
Processed chunk with 50000 rows, found 1345 matches.
Processed chunk with 50000 rows, found 1508 matches.
Processed chunk with 50000 rows, found 1572 matches.
Processed chunk with 50000 rows, found 2721 matches.
Processed chunk with 50000 rows, found 4027 matches.
Processed chunk with 50000 rows, found 3703 matches.
Processed chunk with 50000 rows, found 4291 matches.
Processed chunk with 50000 rows, found 4595 matches.
Processed chunk with 50000 rows, found 4123 matches.
Processed chunk with 50000 rows, found 4048 matches.
Processed chunk with 50000 rows, found 4182 matches.
Processed chunk with 50000 rows, found 4563 matches.
Processed chunk with 50000 rows, found 4523 matches.
Processed chunk with 50000 rows, found 4424 matches.
Processed chunk with 50000 rows, found 4444 matches.
Processed chunk with 50000 rows, found 5102 matches.
Processed chunk with 50000 rows, found 5164 matches.
Processed chunk with 50000 rows, found 4881 matches.
Processed chunk with 50000 rows, found 4215 matches.
Processed chunk with 50000 rows, found 4788 matches.
Processed chunk with 50000 rows, found 5148 matches.
Processed chunk with 50000 rows, found 4691 matches.
Processed chunk with 50000 rows, found 4329 matches.
Processed chunk with 50000 rows, found 4276 matches.
Processed chunk with 50000 rows, found 4842 matches.
Processed chunk with 50000 rows, found 4942 matches.
Processed chunk with 50000 rows, found 5506 matches.
Processed chunk with 50000 rows, found 5733 matches.
Processed chunk with 50000 rows, found 6031 matches.
Processed chunk with 50000 rows, found 5209 matches.
Processed chunk with 50000 rows, found 4734 matches.
Processed chunk with 50000 rows, found 3433 matches.
Processed chunk with 50000 rows, found 3235 matches.
Processed chunk with 50000 rows, found 2955 matches.
Processed chunk with 50000 rows, found 2411 matches.
Processed chunk with 50000 rows, found 2362 matches.
Processed chunk with 50000 rows, found 2488 matches.
Processed chunk with 50000 rows, found 3642 matches.
Processed chunk with 50000 rows, found 3774 matches.
Processed chunk with 50000 rows, found 3545 matches.
Processed chunk with 50000 rows, found 3221 matches.
Processed chunk with 50000 rows, found 2695 matches.
Processed chunk with 50000 rows, found 2230 matches.
Processed chunk with 50000 rows, found 1886 matches.
Processed chunk with 50000 rows, found 2101 matches.
Processed chunk with 50000 rows, found 3134 matches.
Processed chunk with 50000 rows, found 2256 matches.
Processed chunk with 50000 rows, found 1818 matches.
Processed chunk with 50000 rows, found 1644 matches.
Processed chunk with 50000 rows, found 1570 matches.
Processed chunk with 50000 rows, found 2806 matches.
Processed chunk with 50000 rows, found 2294 matches.
Processed chunk with 50000 rows, found 1714 matches.
Processed chunk with 50000 rows, found 1749 matches.
Processed chunk with 50000 rows, found 1467 matches.
Processed chunk with 50000 rows, found 2258 matches.
Processed chunk with 50000 rows, found 2926 matches.
Processed chunk with 50000 rows, found 1384 matches.
Processed chunk with 50000 rows, found 1539 matches.
Processed chunk with 50000 rows, found 1704 matches.
Processed chunk with 50000 rows, found 1717 matches.
Processed chunk with 50000 rows, found 2026 matches.
Processed chunk with 50000 rows, found 2569 matches.
Processed chunk with 50000 rows, found 1676 matches.
Processed chunk with 50000 rows, found 1614 matches.
Processed chunk with 50000 rows, found 1629 matches.
Processed chunk with 50000 rows, found 1669 matches.
Processed chunk with 50000 rows, found 2928 matches.
Processed chunk with 50000 rows, found 2433 matches.
Processed chunk with 50000 rows, found 1735 matches.
Processed chunk with 50000 rows, found 1570 matches.
Processed chunk with 50000 rows, found 1415 matches.
Processed chunk with 50000 rows, found 1943 matches.
Processed chunk with 50000 rows, found 2976 matches.
Processed chunk with 50000 rows, found 2224 matches.
Processed chunk with 50000 rows, found 1730 matches.
Processed chunk with 50000 rows, found 1641 matches.
Processed chunk with 50000 rows, found 1558 matches.
Processed chunk with 50000 rows, found 1959 matches.
Processed chunk with 50000 rows, found 3317 matches.
Processed chunk with 50000 rows, found 2136 matches.
Processed chunk with 50000 rows, found 1467 matches.
Processed chunk with 50000 rows, found 1535 matches.
Processed chunk with 50000 rows, found 1736 matches.
Processed chunk with 50000 rows, found 1500 matches.
Processed chunk with 50000 rows, found 2603 matches.
Processed chunk with 50000 rows, found 2633 matches.
Processed chunk with 50000 rows, found 1552 matches.
Processed chunk with 50000 rows, found 1252 matches.
Processed chunk with 50000 rows, found 1446 matches.
Processed chunk with 50000 rows, found 1295 matches.
Processed chunk with 50000 rows, found 2065 matches.
Processed chunk with 50000 rows, found 2719 matches.
Processed chunk with 50000 rows, found 1406 matches.
Processed chunk with 50000 rows, found 1126 matches.
Processed chunk with 50000 rows, found 941 matches.
Processed chunk with 50000 rows, found 803 matches.
Processed chunk with 50000 rows, found 998 matches.
Processed chunk with 50000 rows, found 1438 matches.
Processed chunk with 50000 rows, found 2768 matches.
Processed chunk with 50000 rows, found 1714 matches.
Processed chunk with 50000 rows, found 940 matches.
Processed chunk with 50000 rows, found 885 matches.
Processed chunk with 50000 rows, found 878 matches.
Processed chunk with 50000 rows, found 988 matches.
Processed chunk with 50000 rows, found 978 matches.
Processed chunk with 50000 rows, found 1275 matches.
Processed chunk with 50000 rows, found 2659 matches.
Processed chunk with 50000 rows, found 1824 matches.
Processed chunk with 50000 rows, found 936 matches.
Processed chunk with 50000 rows, found 886 matches.
Processed chunk with 50000 rows, found 747 matches.
Processed chunk with 50000 rows, found 911 matches.
Processed chunk with 50000 rows, found 836 matches.
Processed chunk with 50000 rows, found 1167 matches.
Processed chunk with 50000 rows, found 2252 matches.
Processed chunk with 50000 rows, found 1869 matches.
Processed chunk with 50000 rows, found 1136 matches.
Processed chunk with 50000 rows, found 800 matches.
Processed chunk with 50000 rows, found 552 matches.
Processed chunk with 50000 rows, found 648 matches.
Processed chunk with 50000 rows, found 842 matches.
Processed chunk with 50000 rows, found 802 matches.
Processed chunk with 50000 rows, found 1039 matches.
Processed chunk with 50000 rows, found 1906 matches.
Processed chunk with 50000 rows, found 2225 matches.
Processed chunk with 50000 rows, found 1307 matches.
Processed chunk with 50000 rows, found 835 matches.
Processed chunk with 50000 rows, found 789 matches.
Processed chunk with 50000 rows, found 805 matches.
Processed chunk with 50000 rows, found 705 matches.
Processed chunk with 50000 rows, found 848 matches.
Processed chunk with 50000 rows, found 1091 matches.
Processed chunk with 50000 rows, found 1499 matches.
Processed chunk with 50000 rows, found 2356 matches.
Processed chunk with 50000 rows, found 1494 matches.
Processed chunk with 50000 rows, found 987 matches.
Processed chunk with 50000 rows, found 871 matches.
Processed chunk with 50000 rows, found 675 matches.
Processed chunk with 50000 rows, found 699 matches.
Processed chunk with 50000 rows, found 1251 matches.
Processed chunk with 50000 rows, found 982 matches.
Processed chunk with 50000 rows, found 1211 matches.
Processed chunk with 50000 rows, found 1995 matches.
Processed chunk with 50000 rows, found 2254 matches.
Processed chunk with 50000 rows, found 1250 matches.
Processed chunk with 50000 rows, found 915 matches.
Processed chunk with 50000 rows, found 697 matches.
Processed chunk with 50000 rows, found 673 matches.
Processed chunk with 50000 rows, found 610 matches.
Processed chunk with 50000 rows, found 744 matches.
Processed chunk with 50000 rows, found 721 matches.
Processed chunk with 50000 rows, found 724 matches.
Processed chunk with 50000 rows, found 925 matches.
Processed chunk with 50000 rows, found 1833 matches.
Processed chunk with 50000 rows, found 1499 matches.
Processed chunk with 50000 rows, found 1002 matches.
Processed chunk with 50000 rows, found 685 matches.
Processed chunk with 50000 rows, found 679 matches.
Processed chunk with 50000 rows, found 577 matches.
Processed chunk with 50000 rows, found 582 matches.
Processed chunk with 50000 rows, found 490 matches.
Processed chunk with 50000 rows, found 505 matches.
Processed chunk with 50000 rows, found 383 matches.
Processed chunk with 50000 rows, found 551 matches.
Processed chunk with 50000 rows, found 1034 matches.
Processed chunk with 50000 rows, found 1353 matches.
Processed chunk with 50000 rows, found 1300 matches.
Processed chunk with 50000 rows, found 889 matches.
Processed chunk with 50000 rows, found 629 matches.
Processed chunk with 50000 rows, found 636 matches.
Processed chunk with 50000 rows, found 586 matches.
Processed chunk with 50000 rows, found 622 matches.
Processed chunk with 50000 rows, found 586 matches.
Processed chunk with 50000 rows, found 512 matches.
Processed chunk with 15362 rows, found 170 matches.

In [6]:
print("jeff")

jeff

In [5]:
df

,NPI,Entity Type Code,Provider Organization Name (Legal Business Name),Provider Last Name (Legal Name),Provider First Name,Provider First Line Business Mailing Address,Provider First Line Business Practice Location Address,Provider Business Practice Location Address State Name,Provider Business Practice Location Address Postal Code,Healthcare Provider Taxonomy Code_1,Healthcare Provider Taxonomy Code_2
0,1306849336,1.0,NaN,TOWNSEND,ERIC,105 SOLANA RD,105 SOLANA RD,FL,320825229.0,1223G0001X,NaN
1,1467455410,1.0,NaN,STRATIGOPOULOS,GEORGE,4808 CLAIREMONT MESA BLVD,4808 CLAIREMONT MESA BLVD,CA,921172100.0,1223G0001X,NaN
2,1851394894,1.0,NaN,GOODMAN,KENNETH,5925 VENTURE PARK,5925 VENTURE PARK,MI,490091859.0,1223G0001X,NaN
3,1265435200,1.0,NaN,HOROWITZ,FRED,1180 N TOWN CENTER DR STE 175,1180 N TOWN CENTER DR STE 175,NV,891446310.0,1223G0001X,122300000X
4,1205839438,1.0,NaN,TRAPP,SCOTT,3832 HOUNDSTOOTH CT,3832 HOUNDSTOOTH CT,VA,232337678.0,1223G0001X,NaN
...,...,...,...,...,...,...,...,...,...,...,...
378747,1538015003,2.0,ANDREW DJAYA DDS INC,NaN,NaN,9316 PAINTER AVE,9316 PAINTER AVE,CA,906052727,1223G0001X,NaN
378748,1710833298,2.0,ROMANS ORTHODONTICS,NaN,NaN,3618 W ANTHEM WAY STE D120,3618 W ANTHEM WAY STE D120,AZ,850860458,1223X0400X,NaN
378749,1841146222,1.0,NaN,RADWAN,ANWAR,1527 SPRUCE ST APT 41A,3223 N BROAD ST,PA,191405007,122300000X,NaN
378750,1598611972,1.0,NaN,SAMPLAWSKI,CAITLIN,3748 W CAROL ANN WAY,145 PALMETTO POINTE RD,SC,295716721,1223D0001X,NaN
378751,1659227049,1.0,NaN,BENNETT,FELISA,219 LENOX ST,219 LENOX ST,TX,756861615,122300000X,NaN

In [6]:
df.columns = [col.strip().lower() for col in df.columns]

In [ ]:
df = df.rename(columns={
    'npi': 'npi',
    'entity type code': 'entity_type_code',
    'provider organization name (legal business name)': 'provider_organization_name',
    'provider first name': 'provider_first_name',
    'provider last name (legal name)': 'provider_last_name',
    'provider first line business mailing address': 'mailing_address',
    'provider first line business practice location address': 'practice_location_address',
    'healthcare provider taxonomy code_1': 'taxonomy_code_1',
    'healthcare provider taxonomy code_2': 'taxonomy_code_2',
    'provider business practice location address postal code': 'practice_location_postal',
    'provider business practice location address state name': 'practice_location_state'
})

In [19]:
df_safe = df.copy()

In [20]:
df_safe['practice_location_postal'] = df_safe['practice_location_postal'].astype(str).str.strip().str[:5].str.zfill(5)

In [22]:
df_safe.to_parquet('../data/processed/npi_dental_providers.parquet', index=False)

In [31]:
[f for f in df.columns if "taxonomy code_" in f.lower()]

['Healthcare Provider Taxonomy Code_1',
 'Healthcare Provider Taxonomy Code_2',
 'Healthcare Provider Taxonomy Code_3',
 'Healthcare Provider Taxonomy Code_4',
 'Healthcare Provider Taxonomy Code_5',
 'Healthcare Provider Taxonomy Code_6',
 'Healthcare Provider Taxonomy Code_7',
 'Healthcare Provider Taxonomy Code_8',
 'Healthcare Provider Taxonomy Code_9',
 'Healthcare Provider Taxonomy Code_10',
 'Healthcare Provider Taxonomy Code_11',
 'Healthcare Provider Taxonomy Code_12',
 'Healthcare Provider Taxonomy Code_13',
 'Healthcare Provider Taxonomy Code_14',
 'Healthcare Provider Taxonomy Code_15']

In [29]:
df = df[use_cols]

In [20]:
value = "122300000X"
matches = df.eq(value).any()

In [23]:
list(matches[matches == True].index)

['Healthcare Provider Taxonomy Code_1', 'Healthcare Provider Taxonomy Code_2']

In [30]:
df.loc[df['Healthcare Provider Taxonomy Code_1'].str.contains(value) | df['Healthcare Provider Taxonomy Code_2'].str.contains(value)]

,NPI,Entity Type Code,Provider Organization Name (Legal Business Name),Provider First Name,Healthcare Provider Taxonomy Code_1,Healthcare Provider Taxonomy Code_2,Healthcare Provider Taxonomy Code_3,Healthcare Provider Taxonomy Code_4,Healthcare Provider Taxonomy Code_5,Healthcare Provider Taxonomy Code_6,Healthcare Provider Taxonomy Code_7,Healthcare Provider Taxonomy Code_8,Healthcare Provider Taxonomy Code_9,Healthcare Provider Taxonomy Code_10,Healthcare Provider Taxonomy Code_11,Healthcare Provider Taxonomy Code_12,Healthcare Provider Taxonomy Code_13,Healthcare Provider Taxonomy Code_14,Healthcare Provider Taxonomy Code_15,Provider Business Practice Location Address Postal Code
393,1265435200,1.0,NaN,FRED,1223G0001X,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,891446310.0
640,1013910025,1.0,NaN,JULIE,122300000X,1223G0001X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,334093206.0
668,1841293834,1.0,NaN,KEVIN,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19041033.0
1106,1457354466,1.0,NaN,A,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,837131986.0
1117,1265435275,1.0,NaN,CHRISTOPHER,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,457509252.0
1127,1164425179,1.0,NaN,KEITH,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,891461256.0
1144,1962405969,1.0,NaN,KIM,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,980121283.0
1159,1316940315,1.0,NaN,SANDRA,1223G0001X,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,902453738.0
1172,1841293842,1.0,NaN,JOEL,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,110104334.0
1176,1487657482,1.0,NaN,GLENN,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,190387454.0
1186,1386647386,1.0,NaN,ANDREW,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,200366501.0
1242,1245233238,1.0,NaN,STUART,122300000X,1223G0001X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,61101893.0
1262,1043213036,1.0,NaN,GERALD,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,945014211.0
1268,1407859499,1.0,NaN,KENNETH,122300000X,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,334093509.0

In [23]:
df1 = pd.read_parquet('../data/processed/npi_dental_providers.parquet')

In [24]:
df1

,npi,entity_type_code,provider_organization_name,provider_first_name,practice_location_state,practice_location_postal,taxonomy_code_1,taxonomy_code_2
0,1306849336,1.0,NaN,ERIC,FL,32082,1223G0001X,NaN
1,1467455410,1.0,NaN,GEORGE,CA,92117,1223G0001X,NaN
2,1851394894,1.0,NaN,KENNETH,MI,49009,1223G0001X,NaN
3,1265435200,1.0,NaN,FRED,NV,89144,1223G0001X,122300000X
4,1205839438,1.0,NaN,SCOTT,VA,23233,1223G0001X,NaN
...,...,...,...,...,...,...,...,...
378747,1538015003,2.0,ANDREW DJAYA DDS INC,NaN,CA,90605,1223G0001X,NaN
378748,1710833298,2.0,ROMANS ORTHODONTICS,NaN,AZ,85086,1223X0400X,NaN
378749,1841146222,1.0,NaN,ANWAR,PA,19140,122300000X,NaN
378750,1598611972,1.0,NaN,CAITLIN,SC,29571,1223D0001X,NaN
378751,1659227049,1.0,NaN,FELISA,TX,75686,122300000X,NaN

In [25]:
df1.shape

(378752, 8)

In [26]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 378752 entries, 0 to 378751
Data columns (total 8 columns):
 #   Column                      Non-Null Count   Dtype
---  ------                      --------------   -----
 0   npi                         378752 non-null  int64
 1   entity_type_code            378752 non-null  float64
 2   provider_organization_name  109089 non-null  str
 3   provider_first_name         269656 non-null  str
 4   practice_location_state     378750 non-null  str
 5   practice_location_postal    378752 non-null  str
 6   taxonomy_code_1             378752 non-null  str
 7   taxonomy_code_2             56688 non-null   str
dtypes: float64(1), int64(1), str(6)
memory usage: 34.3 MB

In [29]:
from dotenv import load_dotenv
import os
load_dotenv()  
CENSUS_API_KEY = os.getenv("CENSUS_API_KEY")

In [31]:
import census

In [32]:
c = census.Census(CENSUS_API_KEY)

In [34]:
import requests

In [49]:
def fetch_cpb_dental(api_key: str) -> pd.DataFrame:
     url = "https://api.census.gov/data/2017/cbp"
     params = {
          'get': 'ESTAB,EMP,PAYANN,NAME',
          'for': 'county:*',
          'NAICS2017': ['62121','621210'],
          'key': api_key
     }
     response = requests.get(url, params=params)
     response.raise_for_status()

     data = response.json()

     df = pd.DataFrame(data[1:], columns=data[0])
     return df

In [46]:
df1 = fetch_cpb_dental(CENSUS_API_KEY)

In [50]:
df2 = fetch_cpb_dental(CENSUS_API_KEY)

In [55]:
df2

     ESTAB  EMP PAYANN                          NAME NAICS2017 state county
0        8   39   1417      Warren County, Tennessee     62121    47    177
1        8   39   1417      Warren County, Tennessee    621210    47    177
2       52  353  18267  Washington County, Tennessee     62121    47    179
3       52  353  18267  Washington County, Tennessee    621210    47    179
4        6   30   1374     Weakley County, Tennessee     62121    47    183
...    ...  ...    ...                           ...       ...   ...    ...
4515     6   21   1928      Nobles County, Minnesota    621210    27    105
4516     5  114   3115        Pine County, Minnesota     62121    27    115
4517     5  114   3115        Pine County, Minnesota    621210    27    115
4518    67  706  41194     Olmsted County, Minnesota     62121    27    109
4519    67  706  41194     Olmsted County, Minnesota    621210    27    109

[4520 rows x 7 columns]

In [56]:
df2.drop_duplicates(subset=['ESTAB','EMP', 'PAYANN', 'NAME', 'state', 'county'])

     ESTAB  EMP PAYANN                          NAME NAICS2017 state county
0        8   39   1417      Warren County, Tennessee     62121    47    177
2       52  353  18267  Washington County, Tennessee     62121    47    179
4        6   30   1374     Weakley County, Tennessee     62121    47    183
6        8   40   1710    Campbell County, Tennessee     62121    47    013
8       36  267  12545       Maury County, Tennessee     62121    47    119
...    ...  ...    ...                           ...       ...   ...    ...
4510     7   55   2181      Martin County, Minnesota     62121    27    091
4512    10   96   4625       Mower County, Minnesota     62121    27    099
4514     6   21   1928      Nobles County, Minnesota     62121    27    105
4516     5  114   3115        Pine County, Minnesota     62121    27    115
4518    67  706  41194     Olmsted County, Minnesota     62121    27    109

[2260 rows x 7 columns]

In [57]:
from census import Census

B19013_001E (median household income)
B01002_001E (median age)
C27001_001E estimate total

    C27001_004E	Estimate!!Total:!!Male:!!Under 19 years:!!With health insurance coverage
    C27001_007E	Estimate!!Total:!!Male:!!19 to 64 years:!!With health insurance coverage
    C27001_010E	Estimate!!Total:!!Male:!!65 years and over:!!With health insurance coverage
    C27001_014E	Estimate!!Total:!!Female:!!Under 19 years:!!With health insurance coverage
    C27001_017E	Estimate!!Total:!!Female:!!19 to 64 years:!!With health insurance coverage
    C27001_020E	Estimate!!Total:!!Female:!!65 years and over:!!With health insurance coverage

In [65]:
resp = requests.get("https://api.census.gov/data/2021/acs/acs5/variables.json")
variables = resp.json()['variables']

b27001_vars = {k: v for k, v in variables.items() if k.startswith('B27001')}
for code, meta in sorted(b27001_vars.items()):
    print(f"{code}: {meta['label']}")

need = []

for code, meta in sorted(b27001_vars.items()):
    if "with" in meta['label'].lower():
        need.append(code)
        print(f"{code}: {meta['label']}")

B27001_001E: Estimate!!Total:
B27001_002E: Estimate!!Total:!!Male:
B27001_003E: Estimate!!Total:!!Male:!!Under 6 years:
B27001_004E: Estimate!!Total:!!Male:!!Under 6 years:!!With health insurance coverage
B27001_005E: Estimate!!Total:!!Male:!!Under 6 years:!!No health insurance coverage
B27001_006E: Estimate!!Total:!!Male:!!6 to 18 years:
B27001_007E: Estimate!!Total:!!Male:!!6 to 18 years:!!With health insurance coverage
B27001_008E: Estimate!!Total:!!Male:!!6 to 18 years:!!No health insurance coverage
B27001_009E: Estimate!!Total:!!Male:!!19 to 25 years:
B27001_010E: Estimate!!Total:!!Male:!!19 to 25 years:!!With health insurance coverage
B27001_011E: Estimate!!Total:!!Male:!!19 to 25 years:!!No health insurance coverage
B27001_012E: Estimate!!Total:!!Male:!!26 to 34 years:
B27001_013E: Estimate!!Total:!!Male:!!26 to 34 years:!!With health insurance coverage
B27001_014E: Estimate!!Total:!!Male:!!26 to 34 years:!!No health insurance coverage
B27001_015E: Estimate!!Total:!!Male:!!35 to 44 years:
B27001_016E: Estimate!!Total:!!Male:!!35 to 44 years:!!With health insurance coverage
B27001_017E: Estimate!!Total:!!Male:!!35 to 44 years:!!No health insurance coverage
B27001_018E: Estimate!!Total:!!Male:!!45 to 54 years:
B27001_019E: Estimate!!Total:!!Male:!!45 to 54 years:!!With health insurance coverage
B27001_020E: Estimate!!Total:!!Male:!!45 to 54 years:!!No health insurance coverage
B27001_021E: Estimate!!Total:!!Male:!!55 to 64 years:
B27001_022E: Estimate!!Total:!!Male:!!55 to 64 years:!!With health insurance coverage
B27001_023E: Estimate!!Total:!!Male:!!55 to 64 years:!!No health insurance coverage
B27001_024E: Estimate!!Total:!!Male:!!65 to 74 years:
B27001_025E: Estimate!!Total:!!Male:!!65 to 74 years:!!With health insurance coverage
B27001_026E: Estimate!!Total:!!Male:!!65 to 74 years:!!No health insurance coverage
B27001_027E: Estimate!!Total:!!Male:!!75 years and over:
B27001_028E: Estimate!!Total:!!Male:!!75 years and over:!!With health insurance coverage
B27001_029E: Estimate!!Total:!!Male:!!75 years and over:!!No health insurance coverage
B27001_030E: Estimate!!Total:!!Female:
B27001_031E: Estimate!!Total:!!Female:!!Under 6 years:
B27001_032E: Estimate!!Total:!!Female:!!Under 6 years:!!With health insurance coverage
B27001_033E: Estimate!!Total:!!Female:!!Under 6 years:!!No health insurance coverage
B27001_034E: Estimate!!Total:!!Female:!!6 to 18 years:
B27001_035E: Estimate!!Total:!!Female:!!6 to 18 years:!!With health insurance coverage
B27001_036E: Estimate!!Total:!!Female:!!6 to 18 years:!!No health insurance coverage
B27001_037E: Estimate!!Total:!!Female:!!19 to 25 years:
B27001_038E: Estimate!!Total:!!Female:!!19 to 25 years:!!With health insurance coverage
B27001_039E: Estimate!!Total:!!Female:!!19 to 25 years:!!No health insurance coverage
B27001_040E: Estimate!!Total:!!Female:!!26 to 34 years:
B27001_041E: Estimate!!Total:!!Female:!!26 to 34 years:!!With health insurance coverage
B27001_042E: Estimate!!Total:!!Female:!!26 to 34 years:!!No health insurance coverage
B27001_043E: Estimate!!Total:!!Female:!!35 to 44 years:
B27001_044E: Estimate!!Total:!!Female:!!35 to 44 years:!!With health insurance coverage
B27001_045E: Estimate!!Total:!!Female:!!35 to 44 years:!!No health insurance coverage
B27001_046E: Estimate!!Total:!!Female:!!45 to 54 years:
B27001_047E: Estimate!!Total:!!Female:!!45 to 54 years:!!With health insurance coverage
B27001_048E: Estimate!!Total:!!Female:!!45 to 54 years:!!No health insurance coverage
B27001_049E: Estimate!!Total:!!Female:!!55 to 64 years:
B27001_050E: Estimate!!Total:!!Female:!!55 to 64 years:!!With health insurance coverage
B27001_051E: Estimate!!Total:!!Female:!!55 to 64 years:!!No health insurance coverage
B27001_052E: Estimate!!Total:!!Female:!!65 to 74 years:
B27001_053E: Estimate!!Total:!!Female:!!65 to 74 years:!!With health insurance coverage
B27001_054E: Estimate!!Total:!!Female:!!65 to 74 years:!!No health insurance coverage
B27001_055E: Estimate!!Total:!!Female:!!75 years and over:
B27001_056E: Estimate!!Total:!!Female:!!75 years and over:!!With health insurance coverage
B27001_057E: Estimate!!Total:!!Female:!!75 years and over:!!No health insurance coverage
B27001_004E: Estimate!!Total:!!Male:!!Under 6 years:!!With health insurance coverage
B27001_007E: Estimate!!Total:!!Male:!!6 to 18 years:!!With health insurance coverage
B27001_010E: Estimate!!Total:!!Male:!!19 to 25 years:!!With health insurance coverage
B27001_013E: Estimate!!Total:!!Male:!!26 to 34 years:!!With health insurance coverage
B27001_016E: Estimate!!Total:!!Male:!!35 to 44 years:!!With health insurance coverage
B27001_019E: Estimate!!Total:!!Male:!!45 to 54 years:!!With health insurance coverage
B27001_022E: Estimate!!Total:!!Male:!!55 to 64 years:!!With health insurance coverage
B27001_025E: Estimate!!Total:!!Male:!!65 to 74 years:!!With health insurance coverage
B27001_028E: Estimate!!Total:!!Male:!!75 years and over:!!With health insurance coverage
B27001_032E: Estimate!!Total:!!Female:!!Under 6 years:!!With health insurance coverage
B27001_035E: Estimate!!Total:!!Female:!!6 to 18 years:!!With health insurance coverage
B27001_038E: Estimate!!Total:!!Female:!!19 to 25 years:!!With health insurance coverage
B27001_041E: Estimate!!Total:!!Female:!!26 to 34 years:!!With health insurance coverage
B27001_044E: Estimate!!Total:!!Female:!!35 to 44 years:!!With health insurance coverage
B27001_047E: Estimate!!Total:!!Female:!!45 to 54 years:!!With health insurance coverage
B27001_050E: Estimate!!Total:!!Female:!!55 to 64 years:!!With health insurance coverage
B27001_053E: Estimate!!Total:!!Female:!!65 to 74 years:!!With health insurance coverage
B27001_056E: Estimate!!Total:!!Female:!!75 years and over:!!With health insurance coverage

In [66]:
need

['B27001_004E',
 'B27001_007E',
 'B27001_010E',
 'B27001_013E',
 'B27001_016E',
 'B27001_019E',
 'B27001_022E',
 'B27001_025E',
 'B27001_028E',
 'B27001_032E',
 'B27001_035E',
 'B27001_038E',
 'B27001_041E',
 'B27001_044E',
 'B27001_047E',
 'B27001_050E',
 'B27001_053E',
 'B27001_056E']

In [72]:
variables = ['B19013_001E', 
            'B01002_001E', 
            'B27001_001E',]

variables.extend(need)

variables

['B19013_001E',
 'B01002_001E',
 'B27001_001E',
 'B27001_004E',
 'B27001_007E',
 'B27001_010E',
 'B27001_013E',
 'B27001_016E',
 'B27001_019E',
 'B27001_022E',
 'B27001_025E',
 'B27001_028E',
 'B27001_032E',
 'B27001_035E',
 'B27001_038E',
 'B27001_041E',
 'B27001_044E',
 'B27001_047E',
 'B27001_050E',
 'B27001_053E',
 'B27001_056E']

In [73]:
c = Census(CENSUS_API_KEY)
variables = ['B19013_001E', 
            'B01002_001E', 
            'B27001_001E',] + need

result = c.acs5.get(variables, {'for': 'zip code tabulation area:*'},
                    year=2021)

df = pd.DataFrame(result)
df

,B19013_001E,B01002_001E,B27001_001E,B27001_004E,B27001_007E,B27001_010E,B27001_013E,B27001_016E,B27001_019E,B27001_022E,...,B27001_032E,B27001_035E,B27001_038E,B27001_041E,B27001_044E,B27001_047E,B27001_050E,B27001_053E,B27001_056E,zip code tabulation area
0,15292.0,43.7,17074.0,411.0,1308.0,777.0,842.0,832.0,1060.0,1121.0,...,424.0,1246.0,682.0,769.0,958.0,1141.0,1234.0,1031.0,785.0,00601
1,18716.0,44.4,37879.0,814.0,2544.0,1709.0,1727.0,2088.0,2272.0,2633.0,...,796.0,2498.0,1677.0,1847.0,2223.0,2537.0,2904.0,2342.0,1737.0,00602
2,16789.0,44.1,48401.0,1082.0,3739.0,2098.0,1962.0,2141.0,2643.0,2907.0,...,1029.0,3526.0,1997.0,2386.0,2868.0,3022.0,3350.0,3308.0,2653.0,00603
3,18835.0,44.9,5751.0,142.0,387.0,297.0,232.0,319.0,384.0,389.0,...,123.0,393.0,194.0,308.0,345.0,346.0,417.0,373.0,332.0,00606
4,21239.0,43.5,26095.0,540.0,1936.0,1076.0,1228.0,1542.0,1545.0,1605.0,...,463.0,1820.0,1188.0,1212.0,1568.0,1951.0,1716.0,1634.0,1362.0,00610
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33769,-666666666.0,-666666666.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0,99923
33770,70625.0,43.3,917.0,25.0,69.0,33.0,19.0,21.0,76.0,51.0,...,8.0,42.0,6.0,42.0,61.0,54.0,46.0,55.0,17.0,99925
33771,58229.0,38.0,1445.0,52.0,119.0,36.0,75.0,101.0,65.0,80.0,...,33.0,108.0,50.0,59.0,38.0,81.0,81.0,69.0,29.0,99926
33772,-666666666.0,-666666666.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,99927
33773,54946.0,45.1,2144.0,84.0,163.0,26.0,103.0,76.0,69.0,158.0,...,51.0,131.0,36.0,87.0,63.0,94.0,132.0,113.0,97.0,99929

In [75]:
insurance_cols = [col for col in df.columns if col.startswith('B27001') and col != 'B27001_001E']

In [76]:
insurance_cols

['B27001_004E',
 'B27001_007E',
 'B27001_010E',
 'B27001_013E',
 'B27001_016E',
 'B27001_019E',
 'B27001_022E',
 'B27001_025E',
 'B27001_028E',
 'B27001_032E',
 'B27001_035E',
 'B27001_038E',
 'B27001_041E',
 'B27001_044E',
 'B27001_047E',
 'B27001_050E',
 'B27001_053E',
 'B27001_056E']

In [ ]:
df = df.replace(-666666666.0, pd.NA)
df[insurance_cols] = df[insurance_cols].apply(pd.to_numeric, errors='coerce')
df['insured_total'] = df[insurance_cols].sum(axis=1)
df['pct_insured'] = df['insured_total'] / df['B27001_001E'].astype(float) * 100

In [82]:
df['pct_insured'].describe()

count    33050.000000
mean        91.420550
std          8.294835
min          0.000000
25%         88.553638
50%         93.478586
75%         96.589839
max        100.000000
Name: pct_insured, dtype: float64

In [83]:
df

,B19013_001E,B01002_001E,B27001_001E,B27001_004E,B27001_007E,B27001_010E,B27001_013E,B27001_016E,B27001_019E,B27001_022E,...,B27001_038E,B27001_041E,B27001_044E,B27001_047E,B27001_050E,B27001_053E,B27001_056E,zip code tabulation area,pct_insured,insured_total
0,15292.0,43.7,17074.0,411.0,1308.0,777.0,842.0,832.0,1060.0,1121.0,...,682.0,769.0,958.0,1141.0,1234.0,1031.0,785.0,00601,95.127094,16242.0
1,18716.0,44.4,37879.0,814.0,2544.0,1709.0,1727.0,2088.0,2272.0,2633.0,...,1677.0,1847.0,2223.0,2537.0,2904.0,2342.0,1737.0,00602,94.991948,35982.0
2,16789.0,44.1,48401.0,1082.0,3739.0,2098.0,1962.0,2141.0,2643.0,2907.0,...,1997.0,2386.0,2868.0,3022.0,3350.0,3308.0,2653.0,00603,93.981529,45488.0
3,18835.0,44.9,5751.0,142.0,387.0,297.0,232.0,319.0,384.0,389.0,...,194.0,308.0,345.0,346.0,417.0,373.0,332.0,00606,96.765780,5565.0
4,21239.0,43.5,26095.0,540.0,1936.0,1076.0,1228.0,1542.0,1545.0,1605.0,...,1188.0,1212.0,1568.0,1951.0,1716.0,1634.0,1362.0,00610,94.979881,24785.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33769,-666666666.0,-666666666.0,13.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,13.0,0.0,99923,100.000000,13.0
33770,70625.0,43.3,917.0,25.0,69.0,33.0,19.0,21.0,76.0,51.0,...,6.0,42.0,61.0,54.0,46.0,55.0,17.0,99925,75.681570,694.0
33771,58229.0,38.0,1445.0,52.0,119.0,36.0,75.0,101.0,65.0,80.0,...,50.0,59.0,38.0,81.0,81.0,69.0,29.0,99926,82.006920,1185.0
33772,-666666666.0,-666666666.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,11.0,0.0,0.0,99927,100.000000,11.0
33773,54946.0,45.1,2144.0,84.0,163.0,26.0,103.0,76.0,69.0,158.0,...,36.0,87.0,63.0,94.0,132.0,113.0,97.0,99929,83.675373,1794.0

In [1]:
df

NameError: name 'df' is not defined

In [9]:
import requests
import io

In [5]:
def fetch_gcspi() -> pd.DataFrame:
    #requests pull: https://www.newyorkfed.org/medialibrary/research/interactives/GSCPI/downloads/gscpi_data.xlsx 
    #pressure index only value column, positive value indicates above average supply chain pressure
    url = "https://www.newyorkfed.org/medialibrary/research/interactives/GSCPI/downloads/gscpi_data.xlsx"
    resp = requests.get(url)
    df = pd.read_excel(resp.content)
    return df[['Date', 'GSCPI']]