In [2]:
import pandas as pd
import numpy as np

In [3]:
nppes = pd.read_parquet('../data/processed/nppes_dental_providers.parquet')
cbp = pd.read_parquet('../data/processed/cbp_dental_2018_2023.parquet')
gcspi = pd.read_parquet('../data/processed/gscpi.parquet')
acs = pd.read_parquet('../data/processed/acs_demographics_2021.parquet')

In [31]:
dfs = [nppes, cbp, acs]

In [ ]:
[col for col in cbp.columns if 'county' in col or 'state' in col]

['practice_location_state', 'county', 'state']

In [31]:
len(acs['county'].values.unique())

326

In [18]:
cbp

,ESTAB,EMP,PAYANN,NAME,NAICS2017,state,county
0,5,27,1072,"Prince Edward County, Virginia",621210,51,147
1,19,201,10488,"Rockingham County, Virginia",621210,51,165
2,3,21,1257,"Scott County, Virginia",621210,51,169
3,40,324,17720,"Spotsylvania County, Virginia",621210,51,177
4,3,13,683,"Clarke County, Virginia",621210,51,043
...,...,...,...,...,...,...,...
13129,4,12,150,"Villalba Municipio, Puerto Rico",621210,72,149
13130,5,23,473,"Yabucoa Municipio, Puerto Rico",621210,72,151
13131,10,35,815,"Yauco Municipio, Puerto Rico",621210,72,153
13132,12,55,2862,"St. Croix Island, United States Virgin Islands",621210,78,010
13133,12,104,6127,"St. Thomas Island, United States Virgin Islands",621210,78,030

In [36]:
acs.groupby('state')['county'].nunique().sum()

np.int64(3221)

In [5]:
crosswalk = pd.read_excel('..\ZIP_COUNTY_122025.xlsx', sheet_name='Export Worksheet', dtype={'ZIP': str, 'COUNTY': str})

<>:1: SyntaxWarning: invalid escape sequence '\Z'
<>:1: SyntaxWarning: invalid escape sequence '\Z'
C:\Users\CMarco\AppData\Local\Temp\ipykernel_13972\392708273.py:1: SyntaxWarning: invalid escape sequence '\Z'
  crosswalk = pd.read_excel('..\ZIP_COUNTY_122025.xlsx', sheet_name='Export Worksheet', dtype={'ZIP': str, 'COUNTY': str})

In [37]:
nppes

,npi,entity_type_code,provider_organization_name,provider_last_name,provider_first_name,mailing_address,practice_location_address,practice_location_state,practice_location_postal,taxonomy_code_1,taxonomy_code_2,county,state
0,1306849336,1.0,NaN,TOWNSEND,ERIC,105 SOLANA RD,105 SOLANA RD,FL,32082,1223G0001X,NaN,082,32
1,1467455410,1.0,NaN,STRATIGOPOULOS,GEORGE,4808 CLAIREMONT MESA BLVD,4808 CLAIREMONT MESA BLVD,CA,92117,1223G0001X,NaN,117,92
2,1851394894,1.0,NaN,GOODMAN,KENNETH,5925 VENTURE PARK,5925 VENTURE PARK,MI,49009,1223G0001X,NaN,009,49
3,1265435200,1.0,NaN,HOROWITZ,FRED,1180 N TOWN CENTER DR STE 175,1180 N TOWN CENTER DR STE 175,NV,89144,1223G0001X,122300000X,144,89
4,1205839438,1.0,NaN,TRAPP,SCOTT,3832 HOUNDSTOOTH CT,3832 HOUNDSTOOTH CT,VA,23233,1223G0001X,NaN,233,23
...,...,...,...,...,...,...,...,...,...,...,...,...,...
378747,1538015003,2.0,ANDREW DJAYA DDS INC,NaN,NaN,9316 PAINTER AVE,9316 PAINTER AVE,CA,90605,1223G0001X,NaN,605,90
378748,1710833298,2.0,ROMANS ORTHODONTICS,NaN,NaN,3618 W ANTHEM WAY STE D120,3618 W ANTHEM WAY STE D120,AZ,85086,1223X0400X,NaN,086,85
378749,1841146222,1.0,NaN,RADWAN,ANWAR,1527 SPRUCE ST APT 41A,3223 N BROAD ST,PA,19140,122300000X,NaN,140,19
378750,1598611972,1.0,NaN,SAMPLAWSKI,CAITLIN,3748 W CAROL ANN WAY,145 PALMETTO POINTE RD,SC,29571,1223D0001X,NaN,571,29
378751,1659227049,1.0,NaN,BENNETT,FELISA,219 LENOX ST,219 LENOX ST,TX,75686,122300000X,NaN,686,75

In [15]:
nppes['county'] = nppes["practice_location_postal"].apply(lambda x: x[2:5])
nppes['state'] = nppes["practice_location_postal"].apply(lambda x: x[0:2])

In [38]:
pd.concat(objs=[df for df in dfs], axis=1, join='inner')

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [ ]:
dfs = [df.set_index(['state', 'county']) for df in dfs]

KeyError: "None of ['state', 'county'] are in the columns"

In [40]:
dfs[0].join(dfs[:1], how='inner')

KeyboardInterrupt:

In [ ]:
test = pd.merge(nppes, )